In [168]:
import pandas as pd
import numpy as np

### Un sistema de ecuaciones lineales se puede resolver reduciendo su forma aumentada. Por ejemplo:
(Tomado de Wikipedia: [Enlace](https://en.wikibooks.org/wiki/Linear_Algebra/Row_Reduction_and_Echelon_Forms))

$3x_{2} - 6x_{3} + 6x_{4} + 4x_{5} = -5$

$3x_{1} - 7x_{2} + 8x_{3} - 5x_{4} + 8x_{5} = 9$

$3x_{1} - 9x_{2} + 12x_{3} - 9x_{4} + 6x_{5} = 15$

$$\begin{bmatrix} 0 & 3 & -6 & 6 & 4 & -5 \\ 3 & -7 & 8 & -5 & 8 & 9 \\ 3 & -9 & 12 & -9 & 6 & 15 \end{bmatrix}$$

In [156]:
coeffs = [[0, 3, -6, 6, 4, -5], [3, -7, 8, -5, 8, 9], [3, -9, 12, -9, 6, 15]]

In [157]:
c = np.array(coeffs)

In [158]:
c

array([[ 0,  3, -6,  6,  4, -5],
       [ 3, -7,  8, -5,  8,  9],
       [ 3, -9, 12, -9,  6, 15]])

### Intercambiamos las filas 0 y 3:

In [159]:
temp = c[0].copy()
c[0] = c[2]
c[2] = temp

In [160]:
c

array([[ 3, -9, 12, -9,  6, 15],
       [ 3, -7,  8, -5,  8,  9],
       [ 0,  3, -6,  6,  4, -5]])

### A la fila 1 le restamos la fila 0:

In [161]:
c[1] = c[1] - c[0]

In [162]:
c

array([[ 3, -9, 12, -9,  6, 15],
       [ 0,  2, -4,  4,  2, -6],
       [ 0,  3, -6,  6,  4, -5]])

### Multiplicamos la fila 1 por 3 y la fila 2 por 2:

In [163]:
c[1] = c[1] * 3
c[2] = c[2] * 2
c

array([[  3,  -9,  12,  -9,   6,  15],
       [  0,   6, -12,  12,   6, -18],
       [  0,   6, -12,  12,   8, -10]])

### A la fila 2 le restamos la fila 1:

In [164]:
c[2] = c[2] - c[1]
c

array([[  3,  -9,  12,  -9,   6,  15],
       [  0,   6, -12,  12,   6, -18],
       [  0,   0,   0,   0,   2,   8]])

### Convertimos los primeros elementos diferentes de cero a 1:

In [165]:
c[0] = c[0] / 3.0
c[1] = c[1] / 6.0
c[2] = c[2] / 2.0
c

array([[ 1, -3,  4, -3,  2,  5],
       [ 0,  1, -2,  2,  1, -3],
       [ 0,  0,  0,  0,  1,  4]])

### Así obtenemos la matriz escalonada:
$$\begin{bmatrix} 1 & -3 & 4 & -3 & 2 & 5 \\ 0 & 1 & -2 & 2 & 1 & -3 \\ 0 & 0 & 0 & 0 & 1 & 4 \end{bmatrix}$$

### Finalmente obtenemos la forma escalonada reducida:

In [166]:
c[0] = c[0] - c[2] * 2
c[1] = c[1] - c[2]
c

array([[ 1, -3,  4, -3,  0, -3],
       [ 0,  1, -2,  2,  0, -7],
       [ 0,  0,  0,  0,  1,  4]])

$$\begin{bmatrix} 1 & -3 & 4 & -3 & 0 & -3 \\ 0 & 1 & -2 & 2 & 0 & -7 \\ 0 & 0 & 0 & 0 & 1 & 4 \end{bmatrix}$$